AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - hash_rockets

Style/SymbolArray:
  Enabled: false # %i[] syntax isn't 1.9.x compatible

Metrics/LineLength:
  Max: 1000

Metrics/MethodLength:
  Max: 15 # Relax slightly from the default of 10

Style/DoubleNegation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context'] # RSpec DSL is expected to have long blocks.

Style/ExpandPathArguments:
  Enabled: false # syntax requires Ruby >= 2.0

Gemspec/RequiredRubyVersion:
  Enabled: false # rubocop compares to gemspec, yet won't allow 1.9 as minimum version
