language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails30.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails31.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails40.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails30.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails31.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails40.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails30.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails31.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails40.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/rails30.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/rails31.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/rails40.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/rails30.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/rails31.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/rails40.gemfile
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
