sudo: false
services:
  - redis-server
language: ruby
# Broken bundler on travis CI - https://github.com/bundler/bundler/issues/2784
before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - jruby-18mode
  - jruby-19mode
  - rbx
jdk:
  - oraclejdk7
env:
  - SKIP_DUMMY_ROLLBAR=true
  - SKIP_DUMMY_ROLLBAR=false
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode

  exclude:
    # Don't run tests for non-jruby environments with the JDK.
    # NOTE: openjdk7 is missing from these exclusions so that Travis will run at least 1 build for the given rvm.
    # TODO: comment as to why these are excluded
    - rvm: 1.9.2
      gemfile: gemfiles/rails31.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails32.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails41.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails30.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails31.gemfile
